# Matrix Multiplication Code Challenges and Solutions to Practice Questions

In [1]:
import numpy as np

## Code Challenge 1: Implement matrix multiplication via layers.

-   Generate two matrices (A and B)
-   Build the product matrix layer-wise (for-loop)
-   Implement the matrix multiplication directly
-   Compare Results.


In [ ]:
# Input matrix dimensions

m = 5 # Outer Dimension 1
n = 2 # Inner Dimension
z = 3 # Puter Dimension 2

# Generate random matrices (with inner dimensions the same)
A = np.random.randn(m,n)
B = np.random.rand(n,z)

# Print A and B
print(f"Matrix A: \n{A}")
print(f"\nMatrix B: \n{B}")

# Preallocate the outer product matrix multiplication 3D array (2 layers of m x z)
op_mm = np.zeros((m,z,n))

for i in range(n):
    for j in range(m):
        for k in range(z):
            op_mm[j,k,i] = A[j,i] * B[i,k]

# Add the two layers
final_op_mm = op_mm[:,:,0] + op_mm[:,:,1]
print("\nMatrix Multiplication via Layer Method:\n", final_op_mm)

 
# MUCH simpler way to do this using outer product
op_mm2 = np.zeros((m,z))

for i in range(n):
        op_mm2 += np.outer(A[:,i], B[i,:]) # The += sign is identical to: op_mm2 = op_mm2 + np.outer(A[:,i], B[i,:])
print("\nSimpler method:\n", op_mm2)


# Calculate using matrix multiplication
mm = np.matmul(A,B)
print(f"\nMatrix Multiplication using the np.matmul function: \n{mm}")

Matrix A: 
[[-1.30435898  0.52870277]
 [ 1.97120672  0.58520005]
 [-1.66818315  0.74456574]
 [-0.4974954  -1.83701702]
 [-0.17544002  0.15840632]]

Matrix B: 
[[0.27091759 0.44923503 0.79289854]
 [0.94544205 0.02903062 0.83647433]]

Matrix Multiplication via Layer Method:
 [[ 0.14648404 -0.57061517 -0.59197803]
 [ 1.08730732  0.90252383  2.05247176]
 [ 0.2520036  -0.7277911  -0.69988985]
 [-1.87157339 -0.2768221  -1.93108095]
 [ 0.10223421 -0.07421517 -0.00660331]]

Simpler method:
 [[ 0.14648404 -0.57061517 -0.59197803]
 [ 1.08730732  0.90252383  2.05247176]
 [ 0.2520036  -0.7277911  -0.69988985]
 [-1.87157339 -0.2768221  -1.93108095]
 [ 0.10223421 -0.07421517 -0.00660331]]

Matrix Multiplication using the np.matmul function: 
[[ 0.14648404 -0.57061517 -0.59197803]
 [ 1.08730732  0.90252383  2.05247176]
 [ 0.2520036  -0.7277911  -0.69988985]
 [-1.87157339 -0.2768221  -1.93108095]
 [ 0.10223421 -0.07421517 -0.00660331]]
