# IntroMatrices Code Challenges and Solutions to Practice Questions

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Code challenge: is matrix-scalar multiplication a linear operation (distributive)?
Test for some random MxN matrices whether s(A+B) = sA + sB

In [36]:
# create matrices
scalar = np.random.randint(-10, 10, 1)  # random scalar
A = np.random.randint(-10, 10, (2,3))  # random matrix A
B = np.random.randint(-10, 10, (2,3))  # random matrix B
print("Scalar (s):\n",scalar)
print("\nMatrix A:\n", A)
print("Matrix B:\n", B)

# pre- and post-multiplication

test1 = scalar * (A + B)
print("\ns(A+B) =\n", test1)

test2 = scalar * A + scalar * B
print("sA + sB =\n", test2)

if np.all(test1 == test2):
    print("\ns(a+b) = sA + sB. \nTherefore, matrix-scalar multiplication is a linear operation (distributive).")
else:    print("\ns(a+b) =/= sA + sB. \nTherefore, matrix-scalar multiplication is NOT a linear operation.")



# note: this is a linear operation, however it originally showed to be incorrect when using the np.random.randn function, probably
# due to the roudning errors in the floating point representation of the numbers.

Scalar (s):
 [1]

Matrix A:
 [[ -1 -10  -9]
 [  4  -9   9]]
Matrix B:
 [[ 8 -1  9]
 [-2  6  5]]

s(A+B) =
 [[  7 -11   0]
 [  2  -3  14]]
sA + sB =
 [[  7 -11   0]
 [  2  -3  14]]

s(a+b) = sA + sB. 
Therefore, matrix-scalar multiplication is a linear operation (distributive).


## Code Challenge: is the trace a linear operation?
-   Determine the relationship between: *tr(A)+tr(B)* and *tr(A+B)*

In [73]:
# Create to random matrices A and B
matrixSize = 3

A = np.random.randn(matrixSize,matrixSize)
B = np.random.randn(matrixSize,matrixSize)
print("\nMatrix A:\n", A)
print("\nMatrix B:\n", B)

# Does tr(a)+tr(b) = tr(a+b)?
test1 = np.trace(A) + np.trace(B)
test2 = np.trace(A + B)
print("\ntr(A) + tr(B)\n=", round(test1,4))
print("tr(A+B)\n=", round(test2,4))

difference = np.round(test1 - test2)
print("\n(tr(A)+tr(B)) - (tr(A+B)) =", difference)
if difference == 0:
    print("\nTherefore, tr(A)+tr(B) = tr(A+B). The trace is a linear operation.")
else:
    print("\nTherefore, tr(A)+tr(B) != tr(A+B). The trace is NOT a linear operation.")




Matrix A:
 [[-0.41587648  0.68271673 -0.83955823]
 [ 1.87981623  0.51617354 -0.03098984]
 [-1.47862185  0.14693455  0.59544436]]

Matrix B:
 [[-0.9621936  -0.51920056 -2.58463948]
 [ 1.09723774 -0.62203011  0.6425382 ]
 [-0.10245608  0.0517754   0.71732949]]

tr(A) + tr(B)
= -0.1712
tr(A+B)
= -0.1712

(tr(A)+tr(B)) - (tr(A+B)) = 0.0

Therefore, tr(A)+tr(B) = tr(A+B). The trace is a linear operation.


-   Determine the relationship between: *tr(lambda\*A)* and *lambda\*tr(A)*

In [60]:
# Create to random matrices A and B
matrixSize = 3

A = np.random.randn(matrixSize,matrixSize)
print("\nMatrix A:\n", A)

# Make some scalar, lambda (l)
l = np.random.randn(1,1)
print("\nScalar (l):\n", l)

# Does tr(lA) = l tr(A)?
test1 = np.trace(l * A)
test2 = l * np.trace(A)

difference = np.round(test1 - test2)

print("\n(tr(lA)) - (l tr(A)) =", difference)
if difference == 0:
    print("\nTherefore, tr(lA) = l tr(A). The trace is a linear operation.")
else:
    print("\nTherefore, tr(lA) != l tr(A). The trace is NOT a linear operation.")


Matrix A:
 [[-0.25735614  0.92461052  0.88984473]
 [ 1.92566076 -1.02935025  0.20757295]
 [-0.67566631  0.90732094 -0.95875659]]

Scalar (l):
 [[0.20410215]]

(tr(lA)) - (l tr(A)) = [[0.]]

Therefore, tr(lA) = l tr(A). The trace is a linear operation.
