#     COURSE: Linear algebra: theory and implementation
##    SECTION: Introduction to matrices

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110

In [1]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [6]:

# square vs. rectangular
S = np.random.randn(5,5) # 5 rows, 5 columns
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)
print(' ')
 
# identity
I = np.eye(3) # 3x3 identity matrix - eye creates identity matrices                   
print(I), print(' ')

# zeros
Z = np.zeros((4,4)) # 4x4 matrix of zeros (must input shape as a tuple).
# must be a tuple, as you can specify the set of numbers: 
# i.e. complexZ = np.zeors((4,4), complex)
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ]) # input a list of numbers, puts this vector on the diagonal
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(U), print(' ')

# concatenate matrices (sizes must match!)

# so, this works:
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)

# but, this doesnt!
# A = np.random.randn(3,2)
# B = np.random.randn(4,4)
# C = np.concatenate((A,B),axis=1)
# print(C)

[[-1.26020165  0.89061118  1.33171661  0.07969477 -0.05661143]
 [ 0.57371464  1.1432026   0.47765451 -0.75507764 -1.03904926]
 [-0.43044786  1.18403069 -0.81885263 -0.41542259  1.18715059]
 [ 1.06716009  0.26912883  0.42058498  1.21039488  0.36158893]
 [-0.83403221 -0.58811564 -0.192789    0.76854731 -0.52920276]]
 
[[ 0.18837242  0.00882431]
 [-0.16269656 -0.37785732]
 [ 0.3048818  -0.22509344]
 [-2.59000479 -0.72234585]
 [-0.91496424 -0.52304754]]
 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[-0.12852225 -0.60748405  0.73255241 -0.45164508  0.21006691]
 [ 0.          0.70546966  0.75961822 -0.51017784 -2.1260467 ]
 [ 0.          0.          1.19942154 -0.6691895   1.07508991]
 [ 0.          0.          0.         -0.60038379 -0.67352247]
 [ 0.          0.          0.          0.         -0.70843106]]
 
[[-0.70274407  0.97137615  2.37645087 -1.22344734  0.217


---
# VIDEO: Matrix addition and subtraction
---


In [ ]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them

# A+B THIS DOESNT WORK AS SIZES DONT MATCH
A+C



# "shifting" a matrix

l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)
# Note that the diagonal elements have been shifted by l, but the rest of the matrix is unchanged  

[[ 0.99208998  1.27769145 -0.01304592  0.27193814  0.19525576]
 [ 0.19837076  0.81218963 -0.68580111 -0.41920725  1.92591862]
 [ 1.10440613  0.378688   -1.29788059  1.37347765  1.73383743]
 [ 0.26808685 -2.48642953 -0.44906869 -0.65921792  0.22971805]
 [-0.83416409  1.41772586 -0.58982632 -0.75300164  1.1560665 ]]
 
[[ 1.02208998  1.27769145 -0.01304592  0.27193814  0.19525576]
 [ 0.19837076  0.84218963 -0.68580111 -0.41920725  1.92591862]
 [ 1.10440613  0.378688   -1.26788059  1.37347765  1.73383743]
 [ 0.26808685 -2.48642953 -0.44906869 -0.62921792  0.22971805]
 [-0.83416409  1.41772586 -0.58982632 -0.75300164  1.1860665 ]]


(None, None, None)


---
# VIDEO: Matrix-scalar multiplication
---


In [10]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print('')
print( s*M )


[[ 2  4]
 [ 4 10]]

[[ 2  4]
 [ 4 10]]


# VIDEO: Transpose

In [ ]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print("Matrix:\n", M), print('')
print("Transpose using .T:\n", M.T), print('') # one transpose
print("Transpose of transpose:\n",M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print("Transpose using np.transpose:\n", np.transpose(M))

# Note: .T does not work unless array is a numpy array, so np.transpose is more general

Matrix:
 [[1 2 3]
 [2 3 4]]

Transpose using .T:
 [[1 2]
 [2 3]
 [3 4]]

Transpose of transpose:
 [[1 2 3]
 [2 3 4]]

Transpose using np.transpose:
 [[1 2]
 [2 3]
 [3 4]]


In [23]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print("Complex Matrix:\n", C), print('')
print("Using the .T operator:\n", C.T), print('')
print("Using the np.tranpose function:\n", np.transpose(C)), print('')
print("Note: the .T and np.transpose functions return the normal transpose, no the Hermitian transpose.\n")

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
hermitian_C = C.conjugate().T
# Another note: the code I used in the video will soon be depreciated; use the above line instead.

print("\nIn python, you first need to use the .conjugate function for the Hermetian Transpose:\n", hermitian_C) # note the sign flips!


Complex Matrix:
 [[4.+1.j 3.+0.j 2.-4.j]]

Using the .T operator:
 [[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

Using the np.tranpose function:
 [[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

Note: the .T and np.transpose functions return the normal transpose, no the Hermitian transpose.


In python, you first need to use the .conjugate function for the Hermetian Transpose:
 [[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# VIDEO: Diagonal and trace
---


In [28]:

M = np.round( 6*np.random.randn(4,4) ) # This creates a random 4x4 matrix, scaled by 6, all rounded to integers
print("Matrix M:\n", M), print(' ')

# extract the diagonal of M
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print("Diagonal (d) of M, using np.diag function:\n", d)
print("\nCreate a vector with d as the diagonal, using the same np.diag function:\n",D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(f"\nTrace using np.trace: {tr}, \nand using sum(np.diag): {tr2}")

Matrix M:
 [[ -4. -11.  -4.   6.]
 [ -4.   2.   4. -10.]
 [  1.  -2.  -4. -10.]
 [ -1.  -8.  -8.  -5.]]
 
Diagonal (d) of M, using np.diag function:
 [-4.  2. -4. -5.]

Create a vector with d as the diagonal, using the same np.diag function:
 [[-4.  0.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  0. -4.  0.]
 [ 0.  0.  0. -5.]]

Trace using np.trace: -11.0, 
and using sum(np.diag): -11.0



---
# VIDEO: Broadcasting matrix arithmetic
---


In [35]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # for np.reshape: options - F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print("Martix A:\n", A), print(' ')
print("Row vector r:\n", r), print(' ')
print("Column vector c:\n", c), print(' ');

Martix A:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
Row vector r:
 [10, 20, 30, 40]
 
Column vector c:
 [100, 200, 300]
 


In [47]:
# broadcast on the rows
print("Martix A:\n", A), print(' ')
print("Row vector r:\n", r), print(' ')
print("Broadcast on the rows (A+r):\n", A+r), print(' ')


# broadcast on the columns
# print(A+c) # This only works if you explicitly reshape c into a column vector

print("\n\nColumn vector c (however, it is in row format currently):\n", c)
c_column = np.reshape(c,(len(c),1))
print("\nc explicity reshaped as a column vector:\n", c_column)
print("\n Broadcast on the columns (A+c):\n",A+c_column) # Reshape c into a column vector


Martix A:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
Row vector r:
 [10, 20, 30, 40]
 
Broadcast on the rows (A+r):
 [[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 


Column vector c (however, it is in row format currently):
 [100, 200, 300]

c explicity reshaped as a column vector:
 [[100]
 [200]
 [300]]

 Broadcast on the columns (A+c):
 [[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
