# Rank Code Challenges and Solutions to Practice Questions

## Code Challenge 1: Create matrices with given rank.

-   Create a 10x10 matrix with rank 4 (using matrix multiplication).
-   Generalise the method to any $m*n$ matrix with $rank=r$.



In [14]:
import numpy as np

# Create 10 x 10 matrix with rank = 4
A = np.random.randint(0, 10, [10, 10])
B = np.random.randint(0, 10, [10, 4])

# Method I used:
# B = np.concatenate([B, B, B[:, 0:2]], axis=1)
# C = A @ B
# print(np.linalg.matrix_rank(A), np.linalg.matrix_rank(B), np.linalg.matrix_rank(C))

# Method wanted:
C = np.random.randint(0, 10, [4, 10])

D = B @ C
print(D.shape)

reduced_rank_A = A @ D
print(np.linalg.matrix_rank(reduced_rank_A))


def set_rank(n, m, r):
    if r > min(n, m):
        raise ValueError("Rank r cannot be greater than number of columns m")
    A = np.random.randint(0, 10, [n, m])
    B = np.random.randint(0, 10, [m, r])
    C = np.random.randint(0, 10, [r, m])
    D = B @ C
    # B = np.concatenate([B, B, B[:, 0:2]], axis=1)

    red_rank_A = A @ D

    return red_rank_A


print(np.linalg.matrix_rank(set_rank(9, 18, 7)))

(10, 10)
4
7


In [15]:
def set_rank(n, m, r):
    if r > min(n, m):
        raise ValueError("Rank r cannot be greater than number of columns m")
    A = np.random.randn(n, m)
    B = np.random.randn(m, r) @ np.random.randn(r, m)
    C = A @ B

    return C


F = np.random.randn(9, 18)
R = set_rank(9, 18, 7)
l = np.random.randint(1, 10, 1)

print("Rank of full-rank matrix:", np.linalg.matrix_rank(F))
print("Rank of reduced-rank matrix:", np.linalg.matrix_rank(R))
print("Scalar:", l)

print("\nRank of scalar multiplied full-rank matrix:", np.linalg.matrix_rank(l * F))
print("Rank of scalar multiplied reduced-rank matrix:", np.linalg.matrix_rank(l * R))

if np.linalg.matrix_rank(l * R) == l * np.linalg.matrix_rank(R):
    print(
        f"\nrank(l*r)({np.linalg.matrix_rank(l*R)}) = l*rank(R)({l*np.linalg.matrix_rank(R)})"
    )
else:
    print(
        f"\nrank(l*r)({np.linalg.matrix_rank(l*R)}) != l*rank(R)({l*np.linalg.matrix_rank(R)})"
    )

Rank of full-rank matrix: 9
Rank of reduced-rank matrix: 7
Scalar: [7]

Rank of scalar multiplied full-rank matrix: 9
Rank of scalar multiplied reduced-rank matrix: 7

rank(l*r)(7) != l*rank(R)([49])


## Code Challenge 2: Summed and multiplied matrix rank.

Rules: 

- $rank(AB) \ge min(rank(A), rank(B))$
- $rank(A+B) \ge rank(A)+rank(b)$

Challenge:

- Generate two matrices (A and B), 2 x 5
- Compute $A^TA$ and $B^TB$, and find rank.
- Find $A^TA$ x $B^TB$ and $A^TA$ + $B^TB$, and compute the rank.



In [1]:
import numpy as np

A = np.random.randn(2, 5)
print(f"Original matrix A: \n{A}")

B = np.random.randn(2, 5)
print(f"Original matrix B: \n{B}")

rankA = np.linalg.matrix_rank(A)
print(f"Rank of A: {rankA}")

rankB = np.linalg.matrix_rank(B)
print(f"Rank of B: {rankB}")

AtA = A.T @ A
print(f"Rank of A^T A: {np.linalg.matrix_rank(AtA)}")

BtB = B.T @ B
print(f"Rank of B^T B: {np.linalg.matrix_rank(BtB)}")

print(f"Rank of A^T A @ B^T B: {np.linalg.matrix_rank(AtA @ BtB)}")
print(f"Rank of A^T A + B^T B: {np.linalg.matrix_rank(AtA + BtB)}")

Original matrix A: 
[[ 1.0085113  -1.15946184 -0.1001255   0.99151175  0.44807699]
 [-0.43546439  0.35267657  0.89165102  0.15227136  1.21353162]]
Original matrix B: 
[[-1.45497936 -1.50518075 -1.18174301 -1.25723871  1.78912947]
 [-0.12142632  0.83742804 -0.67834429 -1.76804689 -0.32353244]]
Rank of A: 2
Rank of B: 2
Rank of A^T A: 2
Rank of B^T B: 2
Rank of A^T A @ B^T B: 2
Rank of A^T A + B^T B: 4


## Code Challenge 3: Is a vector within the span of a set?
Is this vector:
$v = \begin{bmatrix} 1 \\ 2 \\ 3 \\ 4 \end{bmatrix}$ 

In these sets:

$S = \begin{bmatrix} 4 & 0 \\ 3 & 4 \\ 6 & 0 \\ 2 & 1  \end{bmatrix}$ 
$T = \begin{bmatrix} 1 & 0 \\ 2 & 0 \\ 2 & 1 \\ 2 & 2  \end{bmatrix}$ 



In [33]:
v = np.array([1, 2, 3, 4]).T
print(f"Original vector v: {v}")

S = np.vstack([[4, 3, 6, 2], [0, 4, 0, 1]]).T
print(f"Matrix S: \n{S}")

T = np.vstack([[1, 2, 2, 2], [0, 0, 1, 2]]).T
print(f"Matrix T: \n{T}")

print("Span of S and v:")
print(np.linalg.matrix_rank(np.column_stack((S, v))))


print("Span of T and v:")
print(np.linalg.matrix_rank(np.column_stack((T, v))))

Original vector v: [1 2 3 4]
Matrix S: 
[[4 0]
 [3 4]
 [6 0]
 [2 1]]
Matrix T: 
[[1 0]
 [2 0]
 [2 1]
 [2 2]]
Span of S and v:
3
Span of T and v:
2
