# Systems of Equations Code Challenges and Solutions to Practice Questions

## Code Challenge 1: Compute row-reduced echalon form of different matrices

- Square matrix
- Rectangular matrix (tall and wide)
- Linear dependencies on columns vs rows

In [53]:
import numpy as np
import sympy

# Square matrix with full rank
print("=== Square matrix with full rank ===")
A = np.random.randint(0, 10, (3, 3))
A = sympy.Matrix(A)

rref_A = A.rref()[0]
print("RREF:")
print(np.array(rref_A), "\n")


# Wide matrix
print("=== Wide matrix with full rank ===")
B = np.random.randint(0, 10, (4, 7))
B = sympy.Matrix(B)
rref_B = B.rref()[0]
print("RREF:")
print(np.array(rref_B), "\n")

# Tall matrix
print("=== Tall matrix with full rank ===")
C = np.random.randint(0, 10, (5, 2))
C = sympy.Matrix(C)
rref_C = C.rref()[0]
print("RREF:")
print(np.array(rref_C))

=== Square matrix with full rank ===
RREF:
[[1 0 0]
 [0 1 0]
 [0 0 1]] 

=== Wide matrix with full rank ===
RREF:
[[1 0 0 0 -752/1919 -763/1919 -668/1919]
 [0 1 0 0 -1320/1919 -94/1919 134/1919]
 [0 0 1 0 2864/1919 -2157/1919 1605/1919]
 [0 0 0 1 -824/1919 3349/1919 -242/1919]] 

=== Tall matrix with full rank ===
RREF:
[[1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# Square matrix with linear dependent rows
print("=== Square matrix with linearly dependent rows ===")

D = np.random.randint(0, 10, (4, 4))
D[3] = D[2]
D = sympy.Matrix(D)

print("RREF:")
print(np.array(D.rref()[0]))


# Square matrix with linear dependent columns
print("=== Square matrix with linearly dependent columns ===")
E = np.random.randint(0, 10, (4, 4))
E[:, 1] = E[:, 2]
E = sympy.Matrix(E)

print("RREF:")
print(np.array(E.rref()[0]))

=== Square matrix with linearly dependent rows ===
RREF:
[[1 0 0 13/14]
 [0 1 0 -5/7]
 [0 0 1 65/126]
 [0 0 0 0]]
=== Square matrix with linearly dependent columns ===
RREF:
[[1 0 0 0]
 [0 1 1 0]
 [0 0 0 1]
 [0 0 0 0]]
